"""Per-project Node-RED containers (M5.2, D13/D10).

The portal is the spawner; Docker is reached only through the least-privilege socket proxy
(DOCKER_HOST=tcp://socket-proxy:2375). One instance per project: 0.5 CPU / 256 MB, its own named
volume, no host mounts, no published ports, attached to the `flows` network where only Caddy and
the portal can reach it. The editor is gated by Caddy forward_auth → /flows/auth (portal session).
A 30-minute idle culler stops instances; capacity assumption: ≤8 concurrent (see
CLAUDE.md)."""

from __future__ import annotations

import logging
import os
from datetime import UTC, datetime, timedelta
from typing import TYPE_CHECKING

import docker
from docker.types import Mount

if TYPE_CHECKING:
    from sqlalchemy.orm import Session, sessionmaker

    from app.models import Project, ProjectMember

from app.project import as_project
from app.provisioning import require_id
from app.tb_client import Device

log = logging.getLogger(__name__)

# Branded Node-RED (Arabic ar-AR default + label, LTR-only; built by images.yml, nodered-brand/).
# Falls back to upstream only if NODERED_IMAGE is unset (dev without the branded image pulled).
NODERED_IMAGE = os.environ.get(
    "NODERED_IMAGE", f"nodered/node-red:{os.environ.get('NODERED_VERSION', '5.0.6')}"
)
PROJECT = os.environ.get("COMPOSE_PROJECT", "chertiot")
FLOWS_NETWORK = f"{PROJECT}_flows"
IDLE_STOP = timedelta(minutes=30)
FLOWS_DEVICE = "node-red"

SETTINGS_JS = """// Generated by the CHERT IoT portal — edits here are overwritten on restart.
module.exports = {{
    httpAdminRoot: '/u/{project_id}/',
    httpNodeRoot: '/u/{project_id}/api/',
    uiPort: 1880,
    // The editor is protected by the platform login at the proxy; no second password here.
    adminAuth: null,
    editorTheme: {{
        page: {{ title: 'CHERT Node' }},
        header: {{ title: 'CHERT Node', url: 'https://chertiot.com', image: null }},
        palette: {{ }},
        menu: {{ 'menu-item-node-red-version': false }},
        tours: false,
    }},
    functionGlobalContext: {{}},
    logging: {{ console: {{ level: 'info' }} }},
}};
"""


def enabled() -> bool:
    return os.environ.get("FLOWS_ENABLED", "false").lower() == "true"


def client() -> docker.DockerClient:
    return docker.from_env()


def container_name(project_id: str) -> str:
    return f"nodered-{project_id}"


def ensure_flows_device(member: ProjectMember) -> str:
    """A dedicated TB device in the project's tenant; its token is the flow's MQTT credential."""
    with as_project(member) as (_sysadmin, session):
        device = session.find_device(FLOWS_DEVICE)
        if device is None:
            device = session.save_device(
                Device(name=FLOWS_DEVICE, label="Node-RED flows", type="default")
            )
        return session.get_device_credentials(require_id(device, "device")).credentials_id


def _write_settings(dc: docker.DockerClient, volume: str, project_id: str) -> None:
    dc.containers.run(
        "alpine:3.20",
        command=[
            "sh",
            "-c",
            "cat > /data/settings.js <<'EOS'\n"
            + SETTINGS_JS.format(project_id=project_id)
            + "\nEOS\nchown -R 1000:1000 /data",
        ],
        mounts=[Mount(target="/data", source=volume, type="volume")],
        remove=True,
        network_mode="none",
    )


def spawn(project: Project, member: ProjectMember, mqtt_host: str, mqtt_port: int) -> str:
    """Create/start the project's instance. Idempotent. Returns the container name."""
    dc = client()
    name = container_name(project.id)
    token = ensure_flows_device(member)
    volume = f"{PROJECT}_nodered-{project.id}"
    try:
        c = dc.containers.get(name)
        # Migrate to the current image on a version bump (e.g. a new branded ar-AR build): an
        # existing container keeps whatever image it was created with, so reuse it only when the
        # image matches. Flows/credentials live in the named volume, so removing it preserves them.
        if NODERED_IMAGE not in (c.image.tags or []):
            log.info("recreating %s: image %s → %s", name, c.image.tags, NODERED_IMAGE)
            c.remove(force=True)
            raise docker.errors.NotFound(name)
        if c.status != "running":
            # Refresh settings.js so branding/config changes apply the next time it starts,
            # without disrupting an already-running session.
            _write_settings(dc, volume, project.id)
            c.start()
        return name
    except docker.errors.NotFound:
        pass
    dc.images.pull(*NODERED_IMAGE.rsplit(":", 1))
    dc.volumes.create(volume)
    _write_settings(dc, volume, project.id)
    dc.containers.run(
        NODERED_IMAGE,
        name=name,
        detach=True,
        network=FLOWS_NETWORK,
        mounts=[Mount(target="/data", source=volume, type="volume")],
        environment={
            "TB_MQTT_HOST": mqtt_host,
            "TB_MQTT_PORT": str(mqtt_port),
            "TB_ACCESS_TOKEN": token,
            "NODE_OPTIONS": "--max-old-space-size=192",
        },
        nano_cpus=500_000_000,  # 0.5 CPU
        mem_limit="256m",
        pids_limit=256,
        restart_policy={"Name": "unless-stopped"},
        labels={"chertiot.flows.project": project.id},
    )
    log.info("spawned %s", name)
    return name


def stop(project_id: str) -> bool:
    dc = client()
    try:
        c = dc.containers.get(container_name(project_id))
    except docker.errors.NotFound:
        return False
    if c.status == "running":
        c.stop(timeout=10)
    return True


def status(project_id: str) -> str:
    try:
        return str(client().containers.get(container_name(project_id)).status)
    except docker.errors.NotFound:
        return "absent"
    except docker.errors.DockerException:
        return "unavailable"


def ready(project_id: str) -> bool:
    """True only when Node-RED is actually serving the editor — not merely when the container is
    'running' (Docker reports that within a second, but Node-RED needs a few seconds to boot).
    The portal shares the flows network, so it can probe the instance directly."""
    if status(project_id) != "running":
        return False
    import httpx

    try:
        r = httpx.get(f"http://{container_name(project_id)}:1880/u/{project_id}/", timeout=2.0)
        return r.status_code < 500
    except Exception:
        return False


def state(project_id: str) -> str:
    """UI state: 'ready' (open the editor), 'starting' (building), or 'stopped'."""
    st = status(project_id)
    if st != "running":
        return "stopped"
    return "ready" if ready(project_id) else "starting"


def cull_idle(session_factory: sessionmaker[Session]) -> int:
    """Stop instances idle for longer than IDLE_STOP. Returns how many were stopped."""
    from sqlalchemy import select

    from app.models import FlowInstance

    cutoff = datetime.now(UTC) - IDLE_STOP
    stopped = 0
    with session_factory() as db:
        for inst in db.scalars(select(FlowInstance).where(FlowInstance.state == "running")):
            if inst.last_active.replace(tzinfo=UTC) < cutoff:
                if stop(inst.project_id):
                    stopped += 1
                inst.state = "stopped"
        db.commit()
    if stopped:
        log.info("flows culler stopped %d idle instance(s)", stopped)
    return stopped
