"""Per-student Node-RED containers (M3.1, D10).

The portal is the spawner; Docker is reached only through the least-privilege socket proxy
(DOCKER_HOST=tcp://socket-proxy:2375). Every instance: 0.5 CPU / 256 MB, its own named volume,
no host mounts, no published ports, attached to the `flows` network where only Caddy and the
portal can reach it. The editor is gated by Caddy forward_auth → /flows/auth (portal session).
A 30-minute idle culler stops instances; capacity assumption: ≤8 concurrent (see
CLAUDE.md)."""

from __future__ import annotations

import logging
import os
from datetime import UTC, datetime, timedelta

import docker
from docker.types import Mount

from app.provisioning import require_id
from app.student import as_student
from app.tb_client import Device

log = logging.getLogger(__name__)

NODERED_IMAGE = f"nodered/node-red:{os.environ.get('NODERED_VERSION', '5.0.6')}"
PROJECT = os.environ.get("COMPOSE_PROJECT", "chertiot")
FLOWS_NETWORK = f"{PROJECT}_flows"
IDLE_STOP = timedelta(minutes=30)
FLOWS_DEVICE = "node-red"

SETTINGS_JS = """// Generated by the CHERT IoT portal — edits here are overwritten on restart.
module.exports = {{
    httpAdminRoot: '/u/{user_id}/',
    httpNodeRoot: '/u/{user_id}/api/',
    uiPort: 1880,
    // The editor is protected by the platform login at the proxy; no second password here.
    adminAuth: null,
    editorTheme: {{ page: {{ title: 'CHERT IoT flows' }}, tours: false }},
    functionGlobalContext: {{}},
    logging: {{ console: {{ level: 'info' }} }},
}};
"""


def enabled() -> bool:
    return os.environ.get("FLOWS_ENABLED", "false").lower() == "true"


def client() -> docker.DockerClient:
    return docker.from_env()


def container_name(user_id: str) -> str:
    return f"nodered-{user_id}"


def ensure_flows_device(user) -> str:  # noqa: ANN001 — PortalUser (avoid circular import)
    """A dedicated TB device in the student's own tenant; its token is the flow's MQTT
    credential."""
    with as_student(user) as (_sysadmin, student):
        device = student.find_device(FLOWS_DEVICE)
        if device is None:
            device = student.save_device(
                Device(name=FLOWS_DEVICE, label="Node-RED flows", type="default")
            )
        return student.get_device_credentials(require_id(device, "device")).credentials_id


def _write_settings(dc: docker.DockerClient, volume: str, user_id: str) -> None:
    dc.containers.run(
        "alpine:3.20",
        command=[
            "sh",
            "-c",
            "cat > /data/settings.js <<'EOS'\n"
            + SETTINGS_JS.format(user_id=user_id)
            + "\nEOS\nchown 1000:1000 /data/settings.js",
        ],
        mounts=[Mount(target="/data", source=volume, type="volume")],
        remove=True,
        network_mode="none",
    )


def spawn(user, mqtt_host: str, mqtt_port: int) -> str:  # noqa: ANN001
    """Create/start the student's instance. Idempotent. Returns the container name."""
    dc = client()
    name = container_name(user.id)
    token = ensure_flows_device(user)
    volume = f"{PROJECT}_nodered-{user.id}"
    try:
        c = dc.containers.get(name)
        if c.status != "running":
            c.start()
        return name
    except docker.errors.NotFound:
        pass
    dc.images.pull(*NODERED_IMAGE.rsplit(":", 1))
    dc.volumes.create(volume)
    _write_settings(dc, volume, user.id)
    dc.containers.run(
        NODERED_IMAGE,
        name=name,
        detach=True,
        network=FLOWS_NETWORK,
        mounts=[Mount(target="/data", source=volume, type="volume")],
        environment={
            "TB_MQTT_HOST": mqtt_host,
            "TB_MQTT_PORT": str(mqtt_port),
            "TB_ACCESS_TOKEN": token,
            "NODE_OPTIONS": "--max-old-space-size=192",
        },
        nano_cpus=500_000_000,  # 0.5 CPU
        mem_limit="256m",
        pids_limit=256,
        restart_policy={"Name": "unless-stopped"},
        labels={"chertiot.flows.user": user.id},
    )
    log.info("spawned %s", name)
    return name


def stop(user_id: str) -> bool:
    dc = client()
    try:
        c = dc.containers.get(container_name(user_id))
    except docker.errors.NotFound:
        return False
    if c.status == "running":
        c.stop(timeout=10)
    return True


def status(user_id: str) -> str:
    try:
        return str(client().containers.get(container_name(user_id)).status)
    except docker.errors.NotFound:
        return "absent"
    except docker.errors.DockerException:
        return "unavailable"


def cull_idle(session_factory) -> int:  # noqa: ANN001
    """Stop instances idle for longer than IDLE_STOP. Returns how many were stopped."""
    from sqlalchemy import select

    from app.models import FlowInstance

    cutoff = datetime.now(UTC) - IDLE_STOP
    stopped = 0
    with session_factory() as db:
        for inst in db.scalars(select(FlowInstance).where(FlowInstance.state == "running")):
            if inst.last_active.replace(tzinfo=UTC) < cutoff:
                if stop(inst.user_id):
                    stopped += 1
                inst.state = "stopped"
        db.commit()
    if stopped:
        log.info("flows culler stopped %d idle instance(s)", stopped)
    return stopped
