#!/usr/bin/env python3
"""Apply one project's text to the CHERT Keycloak login theme (the ONLY per-project difference).

Reads project.json (see ../project.example.json), writes:
  - messages/messages_en.properties, messages/messages_ar.properties  (all visible text)
  - theme.properties project keys (client id, language-switch path, bullet icons)
then re-stamps asset versions (tools/version_assets.py). Layout, colours, fonts, artwork and
behaviour are never touched.

Usage:  python3 tools/apply_project.py project.json <path-to-theme>/login
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from version_assets import stamp  # noqa: E402

ICONS = {"lock", "wifi", "globe", "users", "shield", "chart", "book", "bolt", "layers", "grid",
         "cpu", "database", "calendar", "heart", "check"}
TEXT_KEYS = ["loginTitle", "eyebrow", "title", "titleAccent", "lead"]
WORD_JOINER = "⁠"


def keep_latin_compounds_together(s: str) -> str:
    """In Arabic text, a Latin compound like "Node-RED" may break at the hyphen and scramble the
    bidi order across lines. A WORD JOINER after the hyphen forbids that break (invisible)."""
    return re.sub(r"([A-Za-z0-9])-(?!⁠)([A-Za-z0-9])", "\\1-" + WORD_JOINER + "\\2", s)


def props_escape(s: str) -> str:
    # Keycloak reads message bundles as UTF-8; only escape what .properties syntax needs.
    return s.replace("\\", "\\\\").replace("\n", "\\n")


def build_messages(lang: str, cfg: dict, product: str) -> str:
    t = cfg[lang]
    missing = [k for k in TEXT_KEYS if not t.get(k)] + ([] if len(t.get("points", [])) == 3 else ["points (exactly 3)"])
    if missing:
        sys.exit(f"project.json [{lang}] missing: {', '.join(missing)}")
    fix = keep_latin_compounds_together if lang == "ar" else (lambda s: s)
    lines = [
        f"loginTitle={props_escape(fix(t['loginTitle']))}",
        f"loginTitleHtml={props_escape(fix(t['loginTitle']))}",
        f"doLogIn={'تسجيل الدخول' if lang == 'ar' else 'Sign in'}",
        f"doRegister={'إنشاء حساب' if lang == 'ar' else 'Create account'}",
        "# ---- Project text (generated by tools/apply_project.py from project.json — edit that file) ----",
        f"chertProduct={props_escape(product)}",
        f"chertAuthEyebrow={props_escape(fix(t['eyebrow']))}",
        f"chertAuthTitle={props_escape(fix(t['title']))}",
        f"chertAuthTitleAccent={props_escape(fix(t['titleAccent']))}",
        f"chertAuthLead={props_escape(fix(t['lead']))}",
    ]
    lines += [f"chertAuthPoint{i}={props_escape(fix(p))}" for i, p in enumerate(t["points"], 1)]
    return "\n".join(lines) + "\n"


def set_prop(text: str, key: str, value: str) -> str:
    line = f"{key}={value}"
    if re.search(rf"^{re.escape(key)}=.*$", text, flags=re.M):
        return re.sub(rf"^{re.escape(key)}=.*$", lambda _m: line, text, flags=re.M)
    return text.rstrip("\n") + "\n" + line + "\n"


def main() -> None:
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    cfg = json.loads(Path(sys.argv[1]).read_text("utf-8"))
    login = Path(sys.argv[2]).resolve()
    product = cfg.get("productName", "").strip()
    if not product:
        sys.exit("project.json: productName is required (the word after CHERT in the logo)")
    icons = cfg.get("icons", ["lock", "wifi", "globe"])
    bad = [i for i in icons if i not in ICONS] + ([] if len(icons) == 3 else ["(need exactly 3)"])
    if bad:
        sys.exit(f"project.json icons invalid: {bad}; choose from {sorted(ICONS)}")

    for lang in ("en", "ar"):
        (login / "messages" / f"messages_{lang}.properties").write_text(build_messages(lang, cfg, product), "utf-8")

    props = login / "theme.properties"
    text = props.read_text("utf-8")
    text = set_prop(text, "chertAppClientId", cfg.get("appClientId", ""))
    text = set_prop(text, "chertLangSwitchPath", cfg.get("langSwitchPath", ""))
    for i, icon in enumerate(icons, 1):
        text = set_prop(text, f"chertPoint{i}Icon", icon)
    props.write_text(text, "utf-8")

    for line in stamp(login):
        print("stamped " + line)
    print(f"applied project '{product}' to {login}")


if __name__ == "__main__":
    main()
